### ISSUE TITLE
Prepare-exportdatabasejobfile.ps1 Cannot specify separate paths for DB and Logs

### ISSUE THREAD

**Issue by cternak** [rubrikinc/rubrik-scripts-for-powershell#102]
**What happened**:
Used the following switches: -TargetDataPath "F:\JAFDB3" -TargetLogPath "E:\JAFDB3_logs"
"exportPath":  "F:\\JAFDB3",
"newFilename":  "JAFDB.ldf"
"exportPath":  "F:\\JAFDB3",   <<<<<<
"newFilename":  "JAFDB_logs.ldf"

**What you expected to happen**:
"exportPath":  "F:\\JAFDB3",
"newFilename":  "JAFDB.ldf"
"exportPath":  "E:\\JAFDB3",   <<<<<<
"newFilename":  "JAFDB_logs.ldf"

**How to reproduce it (as minimally and precisely as possible)**:
Put separate paths.

**Anything else we need to know?**:
nope

**Comment by clumnah** [comment]
The current version of the script asks for both a TargetDataPath and a TargetLogPath. Can you confirm this is still an issue or if this should be closed?
