### ISSUE TITLE
Would be nice for Prepare-ExportDatabaseJobFile.ps1 to have a switch to change the Export DB name

### ISSUE THREAD

**Issue by cternak** [rubrikinc/rubrik-scripts-for-powershell#103]
**What would you like to be added**:
A switch where you can specify the export DB name and Log names (similar to the UI)

**Why is this needed**:
DB is being exported on a daily basis to a server where there is already a DB by this name.  I can manually change the json that is created, but would be nice if this simply created it this way initially.  

**Additional context**

**Comment by clumnah** [comment]
Thank you for the suggestion. I will look to implement during my next round of changes. I may reach out for further input.

________________________________

**Comment by jdrabisz** [comment]
Already wrote and tested.Marcus Henderson has a copy of the code.Case 00098837
    On Monday, August 5, 2019, 01:41:14 PM CDT, Chris Lumnah <notifications@github.com> wrote:  
 
 Thank you for the suggestion. I will look to implement during my next round of changes. I may reach out for further input.

________________________________
