### ISSUE TITLE
Add 2 new privileges to the vCenter Role

### ISSUE THREAD

**Issue by IamTHEvilONE** [rubrikinc/rubrik-scripts-for-powershell#106]
**What would you like to be added**:

Add two more privileges
1. host > config > image
2. storage views > view

**Why is this needed**:
This is needed to automatically install an IO Filter via Update Manager/EAM

**Additional context**
For the Rubrik CDP feature announced in 5.1 mentioned here: https://pages.rubrik.com/20190822-Webinar-NAM-5.1EnhancementOverview-LP.html

**Comment by clumnah** [comment]
What permissions are you referring to?
