### ISSUE TITLE
Which JSON file is proper for Export-RubrikDatabasesJob.ps1

### ISSUE THREAD

**Issue by james7088** [rubrikinc/rubrik-scripts-for-powershell#128]
Two questions:
Q1. Export-RubrikDatabasesJob.ps1; which json component is correct?
```
"Files": [
        {
            "LogicalName": "",
            "Path": "",
            "FileName": ""
          }
        ]
```
or 
```
"Files": [
        {
            "logicalName": "",
            "exportPath": "",
            "newFilename": ""
          }
        ]
```
        
The reason I ask is that 
Q2. There are currently two JSON files listed under the MSSQL directory. Which should be used? 
        1. Export-RubrikDatabasesJobFile.json
        2. JobFile.json

**Comment by clumnah** [comment]
The Prepare-ExportDatabaseJobFile.ps1 scripts outputs the correct format for a JSON file to be used by Export-RubrikDatabasesJob.ps1
