### ISSUE TITLE
Script errors out when when the existing Report is in the Rubrik cluster

### ISSUE THREAD

**Issue by Chris-Doan** [rubrikinc/rubrik-scripts-for-powershell#152]
**What happened**:
When the script is run a second time, it will error out because the report already exists in the Rubrik cluster. Once the report has been deleted, the script runs just fine.

 _PS C:\Users\chris.doan\Documents> .\get-protection-events-servers.ps1
Connected to Rubrik Cluster: amer2-rbk01.rubrikdemo.com
Invoke-WebRequest : Undefined API
At C:\Users\chris.doan\Documents\get-protection-events-servers.ps1:87 char:32
+ ... _response = Invoke-WebRequest -Uri $("https://"+$rubrik_ip+"/api/inte ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Users\chris.doan\Documents\get-protection-events-servers.ps1:91 char:51
+         $report_data = $report_response.Content | ConvertFrom-Json
+                                                   ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
 
Disconnecting from Rubrik
output_file_name : The term 'output_file_name' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the 
path is correct and try again.
At C:\Users\chris.doan\Documents\get-protection-events-servers.ps1:306 char:57
+ ... -host "Script completed, results in output file: $(output_file_name)"
+                                                        ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (output_file_name:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException_ 

**What you expected to happen**:
A new HTML will be created with updated data

**How to reproduce it (as minimally and precisely as possible)**:
Run the script once, and then run it again.

**Anything else we need to know?**:
Rubrik CDM 5.2.1

**Comment by Draper1** [comment]
@Chris-Doan this should be resolved as per PR #155 - let me know if this works.
