### ISSUE TITLE
Export SQL Database with CDC 

### ISSUE THREAD

**Issue by rwyoung01** [rubrikinc/rubrik-scripts-for-powershell#158]
**What happened**:
I was told to use Prepare-ExportDatabaseJobFile.ps1 that would prepare a json file that would help me export databases with CDC.

**What you expected to happen**:
could not get this to work with server that had multiple instances but would on one that did not.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
once I have a json file how does that help me with restoring a database that has Change Data Capture

**Comment by clumnah** [comment]
CDC requires you to restore the database with additional commands. Those commands are not available via Rubrik. The way you do it via the prepare script is run it like you normally would. When you look at the JSON file, you will see a field that says FinishRecovery. This by default is set to true. If you set this to false, your database will be recovered and left in NORECOVERY mode. You can then add to your process to say RESTORE DATABASE [DBNAME] WITH KEEP_CDC.  If you had replication enabled in the database you would do a similar thing, except using KEEP_REPLICATION.
