### ISSUE TITLE
Get "Operation Cancelled" messages when trying to run Start-RubrikOnDemandBackup

### ISSUE THREAD

**Issue by paschott** [rubrikinc/rubrik-scripts-for-powershell#161]
**What happened**:
I try to queue up a set of snapshots to process, but get an "operation canceled" message more often than not.

**What you expected to happen**:
Snapshots to queue up without any errors

**How to reproduce it (as minimally and precisely as possible)**:
Import my creds. Connect to the Rubrik server. Get a list of databases to process. Pass those in to the above script with the set of databases. Sometimes the snapshots start. Sometimes I get an operation canceled message.

**Anything else we need to know?**:
If there's a way to increase the timeout or otherwise work around whatever is canceling the operation, I'd appreciate the hint.

**Comment by clumnah** [comment]
iI ran the above script against a box with 600+ databases on it and i did not see this issue happen once. Are you able to provide more details to this issue? Should I keep the issue open any more?

**Comment by paschott** [comment]
I think this is taken care of now. I found the option to set the timeout for the Rubrik server using
Set-RubrikModuleOption -OptionName DefaultWebRequestTimeout -OptionValue 600

That's high but I was having crazy timeouts with our servers trying to get the connection to work and if I didn't set a higher timeout than needed, I'd get the timeout issue. I think this can be closed.

**Comment by clumnah** [comment]
Great. Thanks for the update. Sorry for just getting to this. Somehow I didn’t get an email for the issue.

I will close it out.

On Jul 14, 2021, at 12:05 PM, Peter Schott ***@***.***> wrote:

﻿

I think this is taken care of now. I found the option to set the timeout for the Rubrik server using
Set-RubrikModuleOption -OptionName DefaultWebRequestTimeout -OptionValue 600

That's high but I was having crazy timeouts with our servers trying to get the connection to work and if I didn't set a higher timeout than needed, I'd get the timeout issue. I think this can be closed.

**Comment by clumnah** [comment]
Closing based on above conversation.
