### ISSUE TITLE
Export-RubrikDatabasesJob.ps1 error

### ISSUE THREAD

**Issue by jdrabisz** [rubrikinc/rubrik-scripts-for-powershell#167]
Good day,
I am migrating my server from Server 2012R2/SQL 2012 to Server 2019/SQL 2019. When I run the Export script I get the following error.

{"message":"Could not open a connection to _servername_:12800. Error while creating
          socket","id":"Connection.OpenFailure","params":{"${host}":"_servername_","${reason}":"Error while creating
          socket","${port}":"12800"}}

I downloaded the most recent powershell script and am still getting the error.

I am running PowerShell v5.1 on both servers.

Thank you,
James

**Comment by jdrabisz** [comment]
DOH! Always something stupid.
Rubrik Backup service wasn't running on the destination server.

**Comment by jaapbrasser** [comment]
Thanks for sharing the solution @jdrabisz!
