### ISSUE TITLE
Report Request - time for backup per database for SQL Server

### ISSUE THREAD

**Issue by paschott** [rubrikinc/rubrik-scripts-for-powershell#168]
**What would you like to be added**:
I'd love a report that would show the actual backup time for each database passed in (or for an instance).

**Why is this needed**:
Currently the Rubrik reports show all backups as part of a batch having the same end time, regardless of when individual databases in the batch completed their backups. This makes it difficult to determine which databases are taking the longest time to actually complete a backup.

**Additional context**

**Comment by clumnah** [comment]
i checked with engineering on this and it isnt possible. While you may have more than one database in a batch being backed up, each one has the same start and end time. This is because the overall steps to finalize the backup is one step for the entire batch. 

I am going to close the issue out.
