### ISSUE TITLE
List of "ObjectType" 

### ISSUE THREAD

**Issue by izzy140-6** [rubrikinc/rubrik-scripts-for-powershell#169]
I have tried "get-rubrikvm" to find what the "ObjectType name is for one of my VMWare machines is and all I get is Name/SLA/ID. But I need to get a list of all of the “ObjectType”, for example, some of the ObjectType I get a return from which work are “NutanixVirtualMachine” , “Mssql” and “WindowsFileSet” , but what I don’t know is what the ObjectType name for the VMWare VMs is.  I have tried “vSphereVM”, “VMWareVirtualMachine” and “vSphere VM”.

If you can provide me with the list of the “ObjectType” then I can select the ones I need.  A developer of the software will know what they have coded in the software as the list of “ObjectType”.

Thank you in advance!

Israel

**Comment by clumnah** [comment]
Here is the list of ObjectTypes 
"VMwareVM","NutanixVM","HyperVVM","MSSQLDB","OracleDB","Fileset","VolumeGroup","ManagedVolume","SLADomain","PhysicalHost",
"NasShare","FilesetTemplate","AvailabilityGroup","DatabaseMount","Event", "EventSeries", "LDAPObject","LogShipping","ManagedVolumeExport",
"VMwareVMLiveMount","RubrikOrganization","Report","RubrikCluster","SQLInstance","vCenterServer","VMwareDatastore","VMwareHost",
"VMwareDatacenter", "VMwareCluster","APIToken","Archive","RubrikCluster", "RubrikClusterNetwork", "RubrikNode", "GuestOSCredential","ReplicationSource","ReplicationTarget",
"SCVMMServer","SyslogServer","RubrikUser","VCDvApp","VCDServer","HyperVHost","NTPServer","NotificationSetting","NutanixCluster","SMBDomain"
