### ISSUE TITLE
Add additional permissions to vCenter user role for AppFlows v1 actions

### ISSUE THREAD

**Issue by oktain89** [rubrikinc/rubrik-scripts-for-powershell#187]
**What would you like to be added**:

Change to create_vCenter_User.ps1 to include new permissions required for AppFlows v1 actions.

**Why is this needed**:

AppFlows needs to modify DR virtual machine resource attributes and requires some additional permissions in this role in order to accomplish these changes.

**Additional context**

**Comment by oktain89** [comment]
An additional missing permission was identified: `VirtualMachine.Provisioning.Clone`

I will create another PR to include this one.

**Comment by DamaniN** [comment]
Fixed by #199
