### ISSUE TITLE
-Inherit is no longer working (invoke-sqlondemand.ps1)

### ISSUE THREAD

**Issue by biaxid3nt317** [rubrikinc/rubrik-scripts-for-powershell#22]
Current 
$requests = $dbs | ForEach-Object{New-RubrikSnapshot -id $_.id -Inherit -Confirm:$False}

Error
New-RubrikSnapshot : Parameter set cannot be resolved using the specified named 
parameters.
At line:24 char:35
+ ... ForEach-Object{New-RubrikSnapshot -id $_.id -Inherit -Confirm:$False}
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-RubrikSnapshot], ParameterBindin 
   gException
    + FullyQualifiedErrorId : AmbiguousParameterSet,New-RubrikSnapshot

Fix
$requests = $dbs | ForEach-Object{New-RubrikSnapshot -id $_.id -SLA 'Bronze' -Confirm:$False}

**Comment by biaxid3nt317** [comment]
Apologies - this error is related to testing with invoke-sqlondemand.ps1

**Comment by clumnah** [comment]
-inherit stopped working after an API change to New-RubrikSnapshot. This script was updated to take the currently assigned SLA and use that value for New-RubrikSnapshot.
