### ISSUE TITLE
Managed Volume need to handled in a different way since any other snapable. It has to be used with Start-RubrikManagedVolumeSnapshot and Stop-RubrikManagedVolumeSnapshot insead of New-RubrikSnapshot

### ISSUE THREAD

**Issue by politzky** [rubrikinc/rubrik-scripts-for-powershell#47]
**What happened**:
Script fails if there is a managed volume in the sla

**What you expected to happen**:
backup of all managed volumes in the given sla

**How to reproduce it (as minimally and precisely as possible)**:
have a managed volume in the source sla and run the script

**Anything else we need to know?**:
If managed volumes are fixed be aware that there is a limit of max 10 running managed volume snaps in parallel

**Comment by politzky** [comment]
Pls fix this section so that it works also for MV.

foreach($SLA in $SLADomains){
    Write-Host ("Gathering snappables from SLA Domain $SLA...")
    $Snappables += Get-RubrikFileset -SLA $SLA
    $Snappables += Get-RubrikVM -SLA $SLA
    **#$Snappables += Get-RubrikManagedVolume -SLA $SLA**
    $Snappables += Get-RubrikDatabase -SLA $SLA
}

**Comment by politzky** [comment]
.

**Comment by politzky** [comment]
Further CDM only supports 10 managed volume snap at the same time. So this must be covered as well in the fix.

**Comment by clumnah** [comment]
Closed with #129
