### ISSUE TITLE
Export-RubrikDatabasesJob.ps1 Fails with DB Not Found Error

### ISSUE THREAD

**Issue by hungryogre** [rubrikinc/rubrik-scripts-for-powershell#55]
**What happened**: Exporting a database from an AG to a non-AG SQL Server fails with `Database AdventureWorks2016 on am1-sql16ag-1ag\ was not found`

**What you expected to happen**: The script will export the backup from the specified recovery point to the location identified in the JSON job file.

**How to reproduce it (as minimally and precisely as possible)**: In Gaia, export the AdventureWorks2016 database from the availability group to another SQL Server instance.

**Anything else we need to know?**: The error comes from line 127 of the script, stating no database was found.  When performing the commands manually it looks like results are actually returned by Rubrik-GetDatabase.

**Comment by rfitzhugh** [comment]
Can one of you take a look at this? @MikeFal @jaapbrasser

**Comment by clumnah** [comment]
Send this to me please.


________________________________

**Comment by clumnah** [comment]
has been fixed with recent code changes.

**Comment by rwyoung01** [comment]
could someone give me an example of the json file.
