### ISSUE TITLE
Reporting/Get-Archive-Backlog.ps1 prevents clean run with Params

### ISSUE THREAD

**Issue by pmilano1** [rubrikinc/rubrik-scripts-for-powershell#59]
**What happened**:
Typo on top of Reporting/Get-Archive-Backlog.ps1 prevents clean run with Params

**What you expected to happen**:
Not the above :)

**How to reproduce it (as minimally and precisely as possible)**:
Just run it and the result is to ignore params and reflect a failure on the line. 

**Anything else we need to know?**:
It just might be the 4 on the topmost line. Also, the examples and authentication docs need clarification.

**Comment by rynardtspies** [comment]
I guess we can close this issue now?
