### ISSUE TITLE
Small typo in the Parse-RubrikSizing.ps1 - outputs "Lob" instead of "Log".

### ISSUE THREAD

**Issue by jseemann** [rubrikinc/rubrik-scripts-for-powershell#62]
**What happened**:
small typo in the Parse-RubrikSizing.ps1 - outputs "Lob" instead of "Log".

<img width="425" alt="Screen Shot 2019-04-08 at 9 59 21 AM" src="https://user-images.githubusercontent.com/44682298/55737482-415c3e00-59f3-11e9-98de-9c6ad2a9e8fb.png">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by rfitzhugh** [comment]
This typo has been fixed. 🦄
