### ISSUE TITLE
Install-RubrikBackupService.ps1 doesn't set default $outfile if not specified on command line

### ISSUE THREAD

**Issue by t6tswb** [rubrikinc/rubrik-scripts-for-powershell#72]
**What happened**:The code attempts to use $OutFile as the install package to copy to remote server but there is no default file set if one isn't passed on the command line.

**What you expected to happen**: should have a default value set.

**How to reproduce it (as minimally and precisely as possible)**:fails if no file is specified on the command line.

**Anything else we need to know?**:developer is already aware of the issue and has the corrected code available.

**Comment by clumnah** [comment]
Resolved with PR #73
