### ISSUE TITLE
Export-RubrikDatabaseBackup.ps1 does not handle Failover clusters correctly. 

### ISSUE THREAD

**Issue by marcus9467** [rubrikinc/rubrik-scripts-for-powershell#76]
**What happened**:
When trying to export between 2 failover clusters the refresh fails because the New-RubrikHost cmdlet expects an actual host vs the clustered name. 

Refreshing clusteredinstancename in Rubrik
Invoke-WebRequest : Host 'clusteredinstancename' conflicts with existing host 'testserver.rubrik.com' because they have the same identity.

**What you expected to happen**:
We should account for failover cluster names and their physical hosts. 
**How to reproduce it (as minimally and precisely as possible)**:
Try to use this script between 2 SQL Fail over clusters. 

**Anything else we need to know?**:

**Comment by clumnah** [comment]
This will be solved with the new cmdlet of Update-RubrikHost. You will run it like so. 

 Get-RubrikHost -Name "am1-sql16fc-1" | Update-RubrikHost

Please run update-module Rubrik to ge tthe new cmdlet. 

I will close the issue, but feel free to reopen if the new cmdlet does not solve your issue.
