### ISSUE TITLE
"ColumnStoreIndex" header missing from Parse-RubrikSizing.ps1

### ISSUE THREAD

**Issue by okhaibai** [rubrikinc/rubrik-scripts-for-powershell#83]
Line 9 in Parse-RubrikSizing.ps1 is missing "ColumnStoreIndex" from the headers list.  Should read as follows:

`$Header="ServerName","SQLVersion","name","recovery_model_desc","SevenDayLogBackupMB","AverageFullMB","AverageFullTimeSec","AverageLogTimeSec","DBTotalSizeMB","AverageLogBackupInterval","ChangeCapture","ColumnStoreIndex","Compression","FILESTREAM","InMemoryOLTP","Partitioning","TransparentDataEncryption" `

**Comment by jaapbrasser** [comment]
Resolved in #93
