### ISSUE TITLE
Json file

### ISSUE THREAD

**Issue by rwyoung01** [rubrikinc/rubrik-scripts-for-powershell#86]
I need an example of the json file

**Comment by clumnah** [comment]
Hello,
Can you be more specific as to what you need? There is a JSON file on the GitHub repo now that shows the structure of what you need. You just need to fill in the values. The values you would provide are explicitly defined in the Powershell script itself in the help section of the script.



________________________________

**Comment by rwyoung01** [comment]
I have never used json files and am new to Rubrik.  Do you have a sample I
could look at.

Russell Young

**Comment by clumnah** [comment]
{
    "RubrikCluster": {
        "Server": "172.172.172.172",
        "Credential": "c:\\temp\\rubrikcredential.cred",
        "Token": ""
    },
    "Databases": [{
    "Source": {
        "AvailabilityGroupName": "AGGroupName",
        "ServerInstance": "",
        "WindowsCluster": "",
        "Name": "DB1"
    },
    "Target": {
        "ServerInstance": "sql1.domain.com",
        "WindowsCluster":"",
        "Name": "DB1_DEV",
        "RecoveryPoint": "latest",
        "Files": [{
            "LogicalName": "db1_data",
            "Path": "f:\\sql\\data\\",
            "FileName": "db1_dev.mdf"
            },
            {
            "LogicalName": "db1_log",
            "Path": "f:\\sql\\logs\\",
            "FileName": "db1_dev.ldf"
            }
        ]
        }
    }
    ]
}


________________________________

**Comment by rwyoung01** [comment]
thanks, just one last question.  What does the credential file look like?

Russell Young

**Comment by clumnah** [comment]
Run the script in the repo called Create-SecurePasswordFile.ps1. It will create you a credential file. You can put the file in any folder on your machine you like, and the Export-RubrikDatabasesJobFile.json should reference that location.

________________________________

**Comment by rwyoung01** [comment]
Thanks so much.

Russell Young
