### ISSUE TITLE
Export-RubrikDatabasejob pass json file in SQL Server Agent Job

### ISSUE THREAD

**Issue by rwyoung01** [rubrikinc/rubrik-scripts-for-powershell#91]
When I use the following script in a SQL Agent job as a cmdshell script type

powershell.exe  D:\Powershell\Rubrik\Export-RubrikDatabasejob.ps1 -Jobfile Export-RubrikDatabaseJobFile.json Nothing happens and I get the following message in the job history

The step did not generate any output.  Process Exit Code 0.  The step succeeded.

If I trying the script as a Powershell type  
D:\Powershell\Rubrik\Export-RubrikDatabasejob.ps1 -Jobfile Export-RubrikDatabaseJobFile.json 

I get the following message  

A job step received an error at line 177 in a PowerShell script. The corresponding line is '    } while ($RubrikRequestInfo.status -notin $ExitList) 	'. Correct the script and reschedule the job. The error information returned by PowerShell is: 'You must provide a value expression on the right-hand side of the '-' operator.  '.  Process Exit Code -1.  The step failed.

The only way it will run is not passing the json file as a parm.   Do you know what I am doing wrong

**Comment by clumnah** [comment]
Are you using the Powershell run type or the Operating system run type?
________________________________

**Comment by rwyoung01** [comment]
i have tried both.  the first example is with the cmdexe and the second
example is with the powershell type.

Russell Young

**Comment by clumnah** [comment]
I am setting up a lab to test this and fix another unrelated problem with this script. I will work on both at the same time and provide a solution.
________________________________

**Comment by rwyoung01** [comment]
I have learned that the Powershell type is running version 2.0 which does
not support the 'notin' command because I am running SQL server 2012 R2.
The cmdexe version is using powershell 3.0 but doesn't work.  Hope this
helps.

Russell Young

**Comment by rwyoung01** [comment]
ok, I moved the script to a SQL Server 2014 and have the SQL Agent job run
as a Powershell Type and am passing the json file.  So the issue is with
SQL 2012 which runs Powershell 2.0.

Russell Young

**Comment by clumnah** [comment]
Please see this article on running powershell with sql agent.

https://www.sqlhammer.com/running-powershell-in-a-sql-agent-job/

For SQL Server 2012, i could get the script to run if i do the below as a job step
powershell.exe -file  E:\Scripts\Export-RubrikDatabasesJob.ps1

I had to modify the script to have this as the param section

param(
    $JobFile = "E:\Scripts\Export-RubrikDatabasesJobFile.json"
)

I am going to test the functionality on other versions of SQL Server.

**Comment by rwyoung01** [comment]
I was not able to run it on SQL 2012 because the Powershell type run
version 2.0 and your code operator 'notin' is not supporter.  But I was
able to get it to run as CMDEXE  but I had to code it this way

powershell.exe D:\Powershell\Rubrik\Export-RubrikDatabasejob.ps1 -jobfile
d:\powershell\rubrik\Export-RubrikDatabaseJobFile.json

When I didn't specify the path to the json file it didn't do anything.  So
we can run it on 2012 when we upgrade powershell to 3.0 and run as CMDEXE.

Russell Young

**Comment by clumnah** [comment]
After some testing, I was able to confirm your way of running things.

For the version thing, there is not much I can do there due to the nature of what is supported as you can see from the blog post article.

Now that you have the script running, shall I close the issue as resolved?
________________________________

**Comment by rwyoung01** [comment]
yes, thanks for helping

Russell Young
