### ISSUE TITLE
Failed to backup all databases using a specific SLA

### ISSUE THREAD

**Issue by calexis19** [rubrikinc/rubrik-scripts-for-powershell#99]
**What happened**:
![image (1)](https://user-images.githubusercontent.com/52928232/61230325-d1e3a200-a6f7-11e9-9612-b7813eff0f2a.png)

**What you expected to happen**: Initiate on-demand backup of all databases on the host with a specific SLA

**How to reproduce it (as minimally and precisely as possible)**: See image

**Anything else we need to know?**:

**Comment by clumnah** [comment]
Resolved with PR #108
